---
name: Conventional commit cocogitto action

description: |
  Check conventional commits compliance and/or automatically release new version

branding:
  icon: git-commit
  color: red

author: Paul Delafosse

inputs:
  git-user:
    description: Git user.name configuration
    required: false
    default: "github-actions"
  git-user-email:
    description: Git user.email configuration
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  command:
    description: The cocogitto command to run (e.g., check, release)
    required: true
  args:
    description: Additional arguments for the cocogitto command
    required: false
    default: ""

outputs:
  version:
    description: Version released
    value: ${{ steps.cog.outputs.version }}
  stdout:
    description: Generated changelog
    value: ${{ steps.cog.outputs.stdout }}

runs:
  using: composite
  steps:
    - run: echo Installing cocogitto
      shell: bash

    - id: install
      run: ${GITHUB_ACTION_PATH}/install.sh
      shell: bash

    - run: echo Running cocogitto
      shell: bash

    - id: add-to-path
      shell: sh
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - id: cog
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/cog.sh \
        "${{ inputs.git-user }}" \
        "${{ inputs.git-user-email }}" \
        "${{ inputs.command }}" \
        "${{ inputs.args }}"
