name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: SemVer release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SemVer release
        id: release
        uses: cocogitto/cocogitto-action@main
        with:
          command: bump
          args: --check-latest-tag
