name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: SemVer release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SemVer release
        id: release
        uses: cocogitto/cocogitto-action@main
        with:
          command: bump
          args: --check-latest-tag

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
